### ISSUE TITLE
Messes up php files

### ISSUE THREAD

**Issue by hirasso** [timtian/gulp-rev-easy#3]
Hi there, just tested your plugin with a php template file (mixed php and html) and it messed things um badly... seems to add `=""` after every appearance of a `?`.

**Comment by timtian** [comment]
can you send some test text to me? the plugin use cheerio, not well formed html may cause some problems.

**Comment by hirasso** [comment]
I will have to make an example file if I get the time, but actually it messes up all my wordpress php files.
