### ISSUE TITLE
Caching incorrect when used with watchers

### ISSUE THREAD

**Issue by MisterGoodcat** [timtian/gulp-rev-easy#5]
Hi! 

First of all thanks for this nice little plug-in.

However, the way caching is implemented doesn't work correctly when the plug-in is used with continuous watchers (like gulp.watch). Hashes then are pulled from the cache even though the contents of the file in question may have changed. 

Proposed solutions: either remove the cache completely, or use something like the change time of the file in question to determine cache invalidation.

**Comment by timtian** [comment]
fix in 1.1.2
use mtime+filename to check cache now.

**Comment by MisterGoodcat** [comment]
Thanks for the quick fix!

I did a fork and used a very similar fix (but you were faster, than me creating a pull request). I used "getTime" comparison instead of caching the coercion value though - nice.
