### ISSUE TITLE
When I put the pictures in script, He have gone on strike

### ISSUE THREAD

**Issue by kyo4311** [timtian/gulp-rev-easy#8]
<script type="text/html">
      <img src="/static/img/xd/banner1.jpg" class="dsb" width="1920" height="266" alt="">
</script>

it is no work

**Comment by timtian** [comment]
cloud you send some code for me.

**Comment by kyo4311** [comment]
like this:
`<div class="imgcenter" style="height: 286px" bind-datalazy="">
    <script type="text/html">
        <img src="/static/img/jh/x4.jpg" class="dsb" width="1920" height="286" alt="">
    </script>
</div>`

i use the script for datalazy ,so, put img in script.

afterwards, i use textarea for datalazy
`<div class="imgcenter" style="height: 286px" bind-datalazy="">
    <textarea>
        <img src="/static/img/jh/x4.jpg" class="dsb" width="1920" height="286" alt="">
    </textarea>
</div>`

**Comment by timtian** [comment]
try update to 1.2.x, set to plain mode, will fix it. and support unwell-formed html
