### ISSUE TITLE
in php laravel blade have a little trouble

### ISSUE THREAD

**Issue by kyo4311** [timtian/gulp-rev-easy#9]
before
`<li @if($router_name=='index') class="curr" @endif><a href="/">home</a></li>`

after
`<li @if($router_name="='index')" class="curr" @endif=""><a href="/">home</a></li>`

**Comment by kyo4311** [comment]
The root of the problem is that cheerio.

`var $ = cheerio.load(file.contents.toString(), {
                decodeEntities: false
            });`

**Comment by timtian** [comment]
try update to 1.2.x, set to plain mode, will fix it. and support unwell-formed html
